import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

shell = "zsh"

[font]
size = 11.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family= "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[cursor]
style = { shape = "Beam", blinking = "On" }

[mouse]
hide_when_typing = true
